version: '3.8'
services:
  backend:
    image: open-deep-coder:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend:ro
      - ./frontend/dist:/app/frontend/dist:ro
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
