name: ci
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
  python-version: ["3.11", "3.12", "3.13"]
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -e .[dev]
      
      - name: Run linting
        run: ruff check .
      
      - name: Check formatting
        run: black --check .
      
      - name: Run type checks
        run: mypy src
      
      - name: Run tests
        run: pytest -q --maxfail=1 --disable-warnings --cov=src --cov=backend --cov-report=xml
      
      - name: Run security checks
        run: |
          bandit -r src/
          safety check
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: matrix.python-version == '3.11'
        with:
          file: ./coverage.xml
          fail_ci_if_error: true