name: Package Release

on:
  push:
    tags:
      - 'v*'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release tarball
        run: |
          git describe --tags --always || true
          VERSION=$(git describe --tags --always)
          ./scripts/package_release.sh
          ls -lah

      - name: Create GitHub Release and upload asset
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload tarball to release
        uses: softprops/action-gh-release@v1
        with:
          files: open-deep-coder-*.tgz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
